WordSmith/urls.py
from django.conf.urls.static import static
# from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from baton.autodiscover import admin

from blog.sitemaps import ArticleSitemap
from users import views as user_views
from django.contrib.auth import views as auth_views
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view

API_TITLE = 'Smith API'
API_DESCRIPTION = 'A Web API for creating and editing blog posts.'
# schema_view = get_schema_view(title=API_TITLE)
schema_view = get_swagger_view(title=API_TITLE)
sitemaps = {'articles': ArticleSitemap, }
urlpatterns = [
    # --- Admin's shell ---
    # path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('baton/', include('baton.urls')),
    # --- APP's ---
    path('anything-but-admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('anything-but-admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    #      name='django.contrib.sitemaps.views.sitemap'),
    # --- API's ---
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/rest-auth/', include('rest_auth.urls')),
    path('api/v1/rest-auth/registration/', include('rest_auth.registration.urls')),
    # --- Documentation ---
    # path('schema/', schema_view),
    path('swagger-docs/', schema_view),
    path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    # --- Authentication ---
    path('oauth/', include('social_django.urls', namespace='social')),
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('export_action/', include("admin_export_action.urls", namespace="admin_export_action")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path, include

from . import views

# urlpatterns = [
# path('', views.API_Root.as_view()),

# path('article/all/', views.AllArticleAPIView.as_view(), name='all_article'),
# path('article/submit/', views.SubmitArticleAPIView.as_view(), name='submit_article'),
# path('article/<int:pk>/update_cover/', views.UpdateCoverArticleAPIView.as_view(), name='update_cover_article'),
# path('article/<int:pk>/update/', views.UpdateArticleAPIView.as_view(), name='update_article'),
# path('article/<int:pk>/delete/', views.DeleteArticleAPIView.as_view(), name='delete_article'),

# path('search/article/title/', views.TitleArticleAPIView.as_view(), name='title_article'),
# http://localhost:8000/api/v1/search/article/title/?article_title=java
# path('search/article/content/', views.ContentArticleAPIView.as_view(), name='content_article'),
# http://localhost:8000/api/v1/search/article/content/?article_content=جاوا
# path('search/article/author/', views.AuthorArticleAPIView.as_view(), name='author_article'),
# http://localhost:8000/api/v1/search/article/author/?author=pooria

# path('articles/', views.ArticleList.as_view(), name='article-list'),
# path('articles/<int:pk>/', views.ArticleDetail.as_view(), name='article-detail'),

# path('users/', views.UserList.as_view(), name='userprofile-list'),
# path('users/<int:pk>/', views.UserDetail.as_view(), name='userprofile-detail'),
#
# path('categories/', views.CategoryList.as_view(), name='category-list'),
# path('category/<int:pk>/', views.CategoryDetail.as_view(), name='category-detail'),
# ]

# ----------------- Dynamic Binding --------------------
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, CategoryViewSet, ArticleViewSet
from .views import TitleArticleAPIView, ContentArticleAPIView, AuthorArticleAPIView

router = DefaultRouter()
router.register('users', UserViewSet)
router.register('articles', ArticleViewSet)
router.register('categories', CategoryViewSet)
urlpatterns = [
    path('search/article/title/', TitleArticleAPIView.as_view(), name='title_article'),
    # http://localhost:8000/api/v1/search/article/title/?article_title=java
    path('search/article/content/', ContentArticleAPIView.as_view(), name='content_article'),
    # http://localhost:8000/api/v1/search/article/content/?article_content=جاوا
    path('search/article/author/', AuthorArticleAPIView.as_view(), name='author_article'),
    # http://localhost:8000/api/v1/search/article/author/?author=pooria
]
urlpatterns += router.urls

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', view=views.ArticlesListView.as_view(), name='index'),
    path('article/<int:pk>/', view=views.ArticleDetailView.as_view(), name='article_detail'),
    path('contact/', view=views.ContactPage.as_view(), name='contact'),
    path('category/', view=views.CategoryArticlesListView.as_view(), name='category'),
    path('category/web/', view=views.CategoryWebArticlesListView.as_view(), name='category_web'),
    path('category/android/', view=views.CategoryAndroidArticlesListView.as_view(), name='category_android'),
    path('category/desktop/', view=views.CategoryDesktopArticlesListView.as_view(), name='category_desktop'),
    path('about/', view=views.AboutPage.as_view(), name='about'),
    path('singlePage/', view=views.SingleStandardPage.as_view(), name='singlePage'),
    path('videoPage/', view=views.VideoPage.as_view(), name='videoPage'),
    path('audioPage/', view=views.AudioPage.as_view(), name='audioPage'),
    # CRUD urls
    path('article/create/', views.CreateArticle.as_view(), name='article_create'),
    path('article/<int:pk>/update/', views.UpdateArticle.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', views.DeleteArticle.as_view(), name='article_delete'),
]

blog/models.py
from datetime import datetime
from PIL import Image
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.urls import reverse


# One-to-one
# user=User()
# user.userprofile
# profile=UserProfile()
# profile.user
# ---
# from blog.models import UserProfile
# from django.contrib.auth.models import User
# profile=UserProfile.objects.get(user__username='Pooria')
# profile.user
# user=User.objects.get(username='Pooria')
# user.userprofiel

# ForeignKey
# new_article=Article()
# new_article.author
# new_author=UserProfile()
# new_author.article_set
# ---
# from blog.models import UserProfile,Article
# new_article=Article.objects.get(author__user__username='Ali')
# new_article.author
# pooria=UserProfile.objects.get(user__username='Pooria')
# pooria.article_set.all()

# Many-to-many
# new_article=Article()
# new_article.??? --> display_category
# new_category=Category()
# new_category.article_set
# ---
# from blog.models import Category,Article
# category.article_set.all()
# category=Category.objects.get(title='Web')
# >>> article=Article.objects.get(title='Java Article')
# >>> for cat in article.category.all():
# ...     print(cat.title)
# ...
# Android
# Web
# Desktop

# How create an Article?
# user=User.objects.create(username='TestShellUser',password='pt13799820')
# profile=UserProfile.objects.create(user=user)
# category=Category.objects.create(title='testCategory')
# article=Article.objects.create(title='testShellArticle',author=profile,content='content of shell test article')
# article.category.add(category)


def validate_file_extension(path):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(str(path))
    valid_extensions = ['.jpg', '.png', '.jpeg']
    if ext[1].lower() not in valid_extensions:
        raise ValidationError('Unsupported file extension.')


class UserProfile(models.Model):
    avatar = models.FileField(default='default_avatar.png', upload_to='user_avatar/',
                              validators=[validate_file_extension],
                              verbose_name=' آواتار ')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=' کاربر ')
    description = RichTextField(max_length=512, null=True, blank=True, verbose_name=' شرح حال ')
    color_code = models.CharField(max_length=6, verbose_name=' کد رنگ ', default='ff0000')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.avatar.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)

    class Meta:
        verbose_name = ' بلاگر '
        verbose_name_plural = ' بلاگرها '
        permissions = (
            ("can_read_private_section", "VIP User"),
            ("user_watcher", "User Watcher"),
        )
        # db_table = 'Profile'
        # constraints = [models.CheckConstraint(check=models.Q(user__username__icontains='admin'),
        #                                       name='user__username__icontains_admin')]
        # constraints = [models.CheckConstraint(check=models.Q(color_code='000000'), name='color_code')]

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


# Custom_Manager
class CustomManager(models.Manager):
    def get_queryset(self):
        return super(CustomManager, self).get_queryset().filter(status='published')


class Article(models.Model):
    STATUS_CHOICES = (
        ('draft', 'آماده انتشار'),
        ('published', 'منتشر شده'),
        ('withdrawn', 'برداشته شده'),
    )
    SELECT = (
        ('fa', 'Persian'),
        ('en', 'English'),
        ('fr', 'French'),
    )
    title = models.CharField(max_length=100, verbose_name=' عنوان ')
    slug = models.SlugField(max_length=100, verbose_name=' لینک ',
                            help_text=' برای بهینه سازی در موتورهای جستجو ')
    category = models.ManyToManyField('Category', verbose_name=' دسته بندی ')
    cover = models.FileField(default='default_article_cover.jpeg', upload_to='article_cover/',
                             validators=[validate_file_extension],
                             verbose_name=' جلد ')
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name=' نویسنده ')
    language = models.CharField(max_length=2, choices=SELECT, default='en', verbose_name=' زبان ')
    content = RichTextUploadingField(verbose_name=' محتوا ')
    publishedTime = models.DateTimeField(default=datetime.now, null=True, blank=True, verbose_name=' تاریخ انتشار ')
    createdTime = models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ ثبت ')
    updatedTime = models.DateTimeField(auto_now=True, verbose_name=' تاریخ ویرایش ')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name=' وضعیت ')
    promote = models.BooleanField(default=False)

    def display_category(self):
        return ', '.join([category.title for category in self.category.all()])

    display_category.short_description = 'دسته بندی'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.cover.path)
        if img.height < 600 or img.width < 800:
            output_size = (800, 600)
            img.thumbnail(output_size)
            img.save(self.cover.path)

    objects = models.Manager()  # The default manager.
    published_objects = CustomManager()  # Custom manager.

    class Meta:
        verbose_name = ' مقاله '
        verbose_name_plural = ' مقاله ها '

    def __str__(self):
        return f'{self.title}'


class Category(models.Model):
    cover = models.FileField(default='default_category_cover.jpg', upload_to='category_cover/',
                             validators=[validate_file_extension], verbose_name=' جلد ')
    created_at = models.DateTimeField(default=datetime.now, verbose_name=' تاریخ ایجاد ')
    title = models.CharField(max_length=100, verbose_name=' عنوان ')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.cover.path)
        if img.height < 600 or img.width < 800:
            output_size = (800, 600)
            img.thumbnail(output_size)
            img.save(self.cover.path)

    class Meta:
        verbose_name = ' دسته بندی '
        verbose_name_plural = ' دسته بندی ها '

    def __str__(self):
        return '{}'.format(self.title)


class ContactUs(models.Model):
    name = models.CharField(max_length=20, verbose_name='نام فرستنده')
    email = models.EmailField(verbose_name='ایمیل فرستنده')
    text = RichTextField(max_length=500, verbose_name='متن فرستاده شده')
    date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ' تماس '
        verbose_name_plural = ' تماس ها '

    def get_absolute_url(self):
        return reverse('blog:contact')


class HandleBaseEmail(models.Model):
    email = models.EmailField(verbose_name='ایمیل عضویت')

    class Meta:
        verbose_name = ' ایمیل عضویت '
        verbose_name_plural = ' ایمیل های عضویت '

blog/views.py
from django.db.models import Q
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from .models import Article, ContactUs, HandleBaseEmail
from .forms import ContactUsForm, SubscribeForm, CreateArticleForm


class ArticlesListView(ListView):
    model = Article
    template_name = 'blog/index.html'
    paginate_by = 4
    queryset = Article.objects.filter(status__exact='published').order_by('publishedTime')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticlesListView, self).get_context_data(**kwargs)
        all_promote_articles = Article.objects.filter(promote=True)
        context.update({
            'all_promote_articles': all_promote_articles,
        })
        return context


class CategoryArticlesListView(ListView):
    model = Article
    paginate_by = 4
    template_name = 'blog/category.html'
    queryset = Article.objects.filter(status__exact='published').order_by('-publishedTime')


class CategoryWebArticlesListView(ListView):
    model = Article
    paginate_by = 4
    template_name = 'blog/category_web.html'
    queryset = Article.objects.filter(Q(category__title__contains='Web') & Q(status__exact='published')).order_by(
        '-publishedTime')


class CategoryAndroidArticlesListView(ListView):
    model = Article
    paginate_by = 4
    template_name = 'blog/category_android.html'
    queryset = Article.objects.filter(category__title__contains='Android', status__exact='published').order_by(
        '-publishedTime')


class CategoryDesktopArticlesListView(ListView):
    model = Article
    paginate_by = 4
    template_name = 'blog/category_desktop.html'
    queryset = Article.objects.filter(category__title__contains='Desktop', status__exact='published').order_by(
        '-publishedTime')


class ContactPage(CreateView):
    form_class = ContactUsForm
    model = ContactUs
    template_name = 'blog/page-contact.html'


class Subscribe(CreateView):
    form_class = SubscribeForm
    model = HandleBaseEmail
    template_name = 'blog/base_with_feature.html'


class AboutPage(TemplateView):
    template_name = 'blog/page-about.html'


class SingleStandardPage(TemplateView):
    template_name = 'blog/single-standard.html'


class VideoPage(TemplateView):
    template_name = 'blog/single-video.html'


class AudioPage(TemplateView):
    template_name = 'blog/single-audio.html'


class ArticleDetailView(DetailView):
    model = Article


# CRUD
class CreateArticle(LoginRequiredMixin, generic.CreateView):
    form_class = CreateArticleForm
    template_name = 'api/article_create.html'
    success_url = '/'


class UpdateArticle(LoginRequiredMixin, generic.UpdateView):
    model = Article
    form_class = CreateArticleForm
    template_name = 'api/article_create.html'
    success_url = '/'


class DeleteArticle(LoginRequiredMixin, generic.DeleteView):
    model = Article
    template_name = 'api/confirm_delete.html'
    success_url = '/'

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>BlogSite{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
    {% block css %}{% endblock %}

    <!-- script
    ================================================== -->
    <script src="{% static 'blog/js/modernizr.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="{% static 'blog/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'blog/favicon.ico' %}" type="image/x-icon">

</head>
<body id="top">

<!-- preloader
================================================== -->
<div id="preloader">
    <div id="loader" class="dots-fade">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>

<!-- header
================================================== -->
<header class="s-header header">

    <div class="header__logo">
        <a class="logo" href="{% url 'blog:index' %}">
            BLOGSITE
        </a>
    </div> <!-- end header__logo -->

    <a class="header__toggle-menu" href="#0" title="Menu"><span>منو</span></a>
    <nav class="header__nav-wrap">

        <h2 class="header__nav-heading h6">هدایت به</h2>

        <ul class="header__nav">
            <li class="current"><a href="{% url 'blog:index' %}" title="">خانه</a></li>
            <li class="has-children">
                <a href="#0" title="">دسته بندی</a>
                <ul class="sub-menu">
                    <li><a href="{% url 'blog:category_android' %}">اندروید</a></li>
                    <li><a href="{% url 'blog:category_web' %}">وب</a></li>
                    <li><a href="{% url 'blog:category_desktop' %}">دسکتاپ</a></li>
                </ul>
            </li>
            <li class="has-children">
                <a href="#0" title="">پست ها</a>
                <ul class="sub-menu">
                    <li><a href="{% url 'blog:videoPage' %}">پست ویدیویی</a></li>
                    <li><a href="{% url 'blog:audioPage' %}">پست صوتی</a></li>
                    <li><a href="{% url 'blog:singlePage' %}">پست استاندارد</a></li>
                </ul>
            </li>
            <li><a href="{% url 'blog:contact' %}" title="">تماس</a></li>
            <li><a href="{% url 'blog:about' %}" title="">درباره</a></li>
            <li class="has-children">
                <a href="#0" title="">کاربران</a>
                <ul class="sub-menu">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'blog:article_create' %}">درج مقاله جدید</a></li>
                        <li><a href="{% url 'profile' %}">پروفایل</a></li>
                        <li><a href="{% url 'logout' %}">خروج</a></li>
                    {% else %}
                        <li><a href="{% url 'register' %}">ثبت نام</a></li>
                        <li><a href="{% url 'login' %}">ورود</a></li>
                    {% endif %}
                </ul>
            </li>
        </ul> <!-- end header__nav -->

        <a href="#0" title="Close Menu" class="header__overlay-close close-mobile-menu">بستن</a>

    </nav> <!-- end header__nav-wrap -->

</header> <!-- s-header -->

<!-- s-content
================================================== -->
{% block content %}{% endblock %}

<!-- s-footer
================================================== -->
<footer class="s-footer">

    <div class="s-footer__main">
        <div class="row">

            <div class="col-six tab-full s-footer__about">

                <h4>درباره BLOGSITE</h4>

                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها
                    و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و
                    کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و
                    آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه
                    ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که
                    تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی
                    دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>

            </div> <!-- end s-footer__about -->

            <div class="col-six tab-full s-footer__subscribe">

                <h4>لورم ایپسوم</h4>

                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و
                    متون بلکه روزنامه مجله در ستون و سطر آنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و
                    کاربردهای.</p>

                <div class="subscribe-form">
                    {% include 'blog/subscribe_form.html' %}
                </div>

            </div> <!-- end s-footer__subscribe -->

        </div>
    </div> <!-- end s-footer__main -->

    <div class="s-footer__bottom">
        <div class="row">

            <div class="col-six">
                <ul class="footer-social">
                    <li>
                        <a href="#0"><i class="fab fa-facebook"></i></a>
                    </li>
                    <li>
                        <a href="#0"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="#0"><i class="fab fa-instagram"></i></a>
                    </li>
                    <li>
                        <a href="#0"><i class="fab fa-youtube"></i></a>
                    </li>
                    <li>
                        <a href="#0"><i class="fab fa-pinterest"></i></a>
                    </li>
                </ul>
            </div>

            <div class="col-six">
                <div class="s-footer__copyright">
                        <span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script>
                            All rights reserved | This template is made with
                            <i class="fa fa-heart" aria-hidden="true"></i>
                            by
                            <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
                </div>
            </div>

        </div>
    </div> <!-- end s-footer__bottom -->

    <div class="go-top">
        <a class="smoothscroll" title="Back to Top" href="#top"></a>
    </div>

</footer> <!-- end s-footer -->

<!-- Java Script
================================================== -->
<script src="{% static 'blog/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'blog/js/plugins.js' %}"></script>
<script src="{% static 'blog/js/main.js' %}"></script>
{% block script %}{% endblock %}

</body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}{{ super }} | Category{% endblock %}

<!-- s-content
================================================== -->
{% block content %}

    <section class="s-content s-content--top-padding">

        <div class="row narrow">
            <div class="col-full s-content__header" data-aos="fade-up">
                <h1 class="display-1 display-1--with-line-sep">دسته بندی ها</h1>
                <p class="lead">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک
                    است
                    چاپگرها و متون بلکه روزنامه مجله در ستون و سطر آنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد
                    نیاز و
                    کاربردهای</p>
            </div>
        </div>

        <div class="row entries-wrap wide">
            <div class="entries">
                {% for article in article_list %}

                    <article class="col-block">

                        <div class="item-entry" data-aos="zoom-in">
                            <div class="item-entry__thumb">
                                <a href="{% url 'blog:article_detail' article.id %}" class="item-entry__thumb-link">
                                    <img src="{{ article.cover.url }}" alt="">
                                </a>
                            </div>

                            <div class="item-entry__text">
                                <div class="item-entry__cat">
                                    <a href="{% url 'blog:category' %}">{{ article.category.title }}</a>
                                </div>

                                <h1 class="item-entry__title"><a href="{% url 'blog:singlePage' %}">{{ article.title }}</a></h1>

                                <div class="item-entry__date">
                                    <a href="{% url 'blog:article_detail' article.id %}">{{ article.publishedTime.date }}</a>
                                </div>
                            </div>
                        </div> <!-- item-entry -->

                    </article> <!-- end article -->
                {% endfor %}

            </div> <!-- end entries -->
        </div> <!-- end entries-wrap -->

        <div class="row pagination-wrap">
            <div class="col-full">
                <nav class="pgn" data-aos="fade-up">
                    <ul>
                        {% if is_paginated %}
                            {% if page_obj.has_previous %}
                                <li><a class="btn btn-outline-info mb-4" href="?page=1">First</a></li>
                                <li><a class="btn btn-outline-info mb-4"
                                       href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                                {% if page_obj.number == num %}
                                    <li><a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a></li>
                                {% elif num > page_obj.number|add:'-3' and  num < page_obj.number|add:'2' %}
                                    <li><a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li><a class="btn btn-outline-info mb-4"
                                       href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                <li><a class="btn btn-outline-info mb-4"
                                       href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                            {% endif %}
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>

    </section> <!-- end s-content -->

{% endblock %}

blog/templates/blog/subscribe_form.html
<form id="mc-form" class="group" method="post" action="">
    {% csrf_token %}
{#    <input type="email" value="" name="EMAIL" class="email" id="mc-email"#}
{#           placeholder="Email Address" required="">#}
    {{ form.email }}

    <input type="submit" name="subscribe" value="ارسال">

    <label for="mc-email" class="subscribe-message"></label>
</form>